In [1]:
import pandas as pd
import numpy as np

In [2]:
# numpy basics

arr = np.array([1,2,3,4,5])
print("1d array: ",arr)
arr2 = np.array([[1,2,3],[4,5,6]])
print("2d array: ",arr2)


# list vs numpy array
py_list = [1,2,3]   # [1,2,3,1,2,3]
print("Multiply Python list by 2: ",py_list * 2)

numpy_array = np.array([1,2,3])     # [2,6,8]
print("numpy_array mutiplication: ",numpy_array*2)

1d array:  [1 2 3 4 5]
2d array:  [[1 2 3]
 [4 5 6]]
Multiply Python list by 2:  [1, 2, 3, 1, 2, 3]
numpy_array mutiplication:  [2 4 6]


In [3]:
# time compairesion

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("Time1: ",time.time() - start)

start = time.time()
numpy_array = np.arange(10000)*2
print("Time2: ",time.time() - start)


Time1:  0.00749516487121582
Time2:  0.0002338886260986328


In [4]:
# zero matix in numpy
zeros = np.zeros([4,1])
print(zeros)

# ones matrix
ones = np.ones([2,3])
print(ones)

# cunstant matrix
random = np.full((3,3),7)
print(random)

[[0.]
 [0.]
 [0.]
 [0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
df = pd.DataFrame(np.random.rand(10,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
print(df)

          A         B         C         D         E
0  0.919396  0.033557  0.182405  0.854103  0.202217
1  0.029519  0.714704  0.018106  0.685478  0.528551
2  0.379515  0.096097  0.723172  0.707843  0.623110
3  0.245291  0.588308  0.299319  0.332778  0.105104
4  0.215205  0.698527  0.126317  0.851323  0.078050
5  0.960210  0.953903  0.504374  0.406894  0.910672
6  0.998298  0.075666  0.979040  0.238093  0.985980
7  0.109455  0.656296  0.136472  0.262016  0.745802
8  0.682682  0.980146  0.696855  0.331116  0.767406
9  0.350424  0.150387  0.460065  0.888136  0.167651
